config/routes.rb
Rails.application.routes.draw do
  resources :shuttle_cars

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    get 'datatable_i18n', to: 'datatables#datatable_i18n'
  end

  get 'bills/current', to: 'bills#current', as: 'current_bill'
  get 'bills/old', to: 'bills#old', as: 'old_bills'
  post 'bills/add_jobs', to: 'bills#add_jobs', as: 'add_jobs_to_bill'
  post 'bills/delete_current', to: 'bills#delete_current', as: 'delete_current_bill'
  post 'bills/pay/:id', to: 'bills#pay', as: 'pay_bill'
  get 'bills/sixt_bill/:id', to: 'bills#sixt_bill', as: 'sixt_bill'
  get 'bills/complete_bill/:id', to: 'bills#complete_bill', as: 'complete_bill'
  get 'bills/drivers_bill/:id', to: 'bills#drivers_bill', as: 'drivers_bill'
  resources :bills
  devise_for :users
  get 'users/invitation', to: 'jobs#new'
  resources :users

  resources :companies
  get 'routes/show_new', to: 'routes#show_new', as: 'new_routes'
  resources :routes

  resources :drivers

  resources :addresses

  post 'jobs/add_co_driver/', to:'jobs#add_co_driver', as: 'job_add_co_driver'
  get 'jobs/create_sixt/', to: 'jobs#create_sixt', as: 'job_create_sixt'
  post 'jobs/create_shuttle/', to: 'jobs#create_shuttle', as: 'job_create_shuttle'
  get 'jobs/new_sixt/', to: 'jobs#new_sixt', as: 'job_new_sixt'
  get 'jobs/new_shuttle/', to: 'jobs#new_shuttle', as: 'new_shuttle_job'
  get 'jobs/change_to_shuttle/:id', to: 'jobs#change_to_shuttle', as: 'job_change_to_shuttle'
  get 'jobs/unset_shuttle/:id', to: 'jobs#unset_shuttle', as: 'job_unset_shuttle'
  post 'jobs/add_to_current_bill/:id', to: 'jobs#add_to_current_bill', as: 'add_job_to_current_bill'
  post 'jobs/remove_from_current_bill/:id', to: 'jobs#remove_from_current_bill', as: 'remove_job_from_current_bill'
  get 'jobs/add_shuttle_breakpoint/:id', to: 'jobs#add_shuttle_breakpoint', as: 'job_add_shuttle_breakpoint'
  get 'jobs/remove_shuttle_breakpoint/:id', to: 'jobs#remove_shuttle_breakpoint', as: 'job_remove_shuttle_breakpoint'
  get 'jobs/change_breakpoint_distance/:id', to: 'jobs#change_breakpoint_distance', as: 'job_change_breakpoint_distance'
  get 'jobs/change_breakpoint_address/:id', to: 'jobs#change_breakpoint_address', as: 'job_change_breakpoint_address'
  get 'jobs/add_shuttle_passenger/:id', to: 'jobs#add_shuttle_passenger', as: 'job_add_shuttle_passenger'
  get 'jobs/remove_shuttle_passenger/:id', to: 'jobs#remove_shuttle_passenger', as: 'job_remove_shuttle_passenger'
  get 'jobs/change_abroad_start_time/:id', to: 'jobs#change_abroad_start_time', as: 'job_change_abroad_start_time'
  get 'jobs/change_abroad_end_time/:id', to: 'jobs#change_abroad_end_time', as: 'job_change_abroad_end_time'
  get 'jobs/remove_leg_abroad_time_end/:id', to: 'jobs#remove_leg_abroad_time_end', as: 'remove_leg_abroad_time_end'
  get 'jobs/remove_leg_abroad_time_start/:id', to: 'jobs#remove_leg_abroad_time_start', as: 'remove_leg_abroad_time_start'
  get 'jobs/print_job/:id', to: 'jobs#print_job', as: 'print_job'
  post 'jobs/delete/:id', to: 'jobs#destroy', as: 'job_delete'
  get 'jobs/multible_cars/:job_amount', to: 'jobs#multible_cars', as: 'job_multible_cars'
  get 'jobs/set_to_print/:id', to: 'jobs#set_to_print', as: 'job_set_to_print'

  resources :jobs
  get 'jobs_ajax/show_all', to: 'jobs#show_all'
  get 'jobs_ajax/show_regular_jobs', to: 'jobs#show_regular_jobs'

  get 'auslandszeiten/auslandszeiten_pro_fahrer/', to: 'abroad_times#show_driver', as: 'get_abroad_drives_for_driver'
  get 'auslandszeiten/index', to: 'abroad_times#index', as: 'abroad_time_index'
  get 'auslandszeiten/:month_string', to: 'abroad_times#show', as: 'show_abroad_times'

  get 'ueberstunden/fahrer/', to: 'overtimes#show_driver', as: 'get_overtimes_for_driver'
  get 'ueberstunden/index', to: 'overtimes#index', as: 'overtimes_index'
  get 'ueberstunden/:month_string', to: 'overtimes#show', as: 'show_overtimes'

  root 'jobs#index'

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy, :remove_from_current_bill,
    :add_to_current_bill, :print_job, :set_to_print, :add_shuttle_breakpoint, :remove_shuttle_breakpoint,
    :change_breakpoint_distance, :add_shuttle_passenger, :remove_shuttle_passenger,
    :change_breakpoint_address, :change_to_shuttle, :set_shuttle_route_and_pay, :unset_shuttle,
    :change_abroad_start_time, :change_abroad_end_time, :remove_leg_abroad_time_end, :remove_leg_abroad_time_start ]
  before_action :check_transfair, except: [ :multible_cars, :create_sixt, :new_sixt, :index  ]

  before_action :check_editable, only: [ :add_shuttle_breakpoint, :remove_shuttle_breakpoint,
    :add_shuttle_passenger, :remove_shuttle_passenger,:update, :edit, :add_to_current_bill, :change_breakpoint_distance,
    :change_breakpoint_address, :change_to_shuttle, :set_shuttle_route_and_pay, :unset_shuttle ]

  before_action :make_empty_times_empty, only: [:create, :update]
  # GET /jobs
  # GET /jobs.json
  def index
    redirect_to job_new_sixt_path unless current_user.is_intern?
  end

  def add_co_driver # just add graphical, real add at update or create
    @drivers = Driver.get_active
    @number_of_co_drivers = params[:number_of_co_drivers].to_i + 1
    respond_to do | format |
      format.html { redirect_to jobs_path }
      format.js { render 'add_co_driver.js.erb' }
    end
  end

  def add_shuttle_breakpoint
    count = params[:count].to_i
    @job.add_shuttle_breakpoint count
    respond_to do | format |
      @shuttle_data = @job.get_shuttle_data
      @drivers = Driver.get_active
      @addresses = Address.get_active
      format.js { render 'rerender_shuttle.js.erb' }
    end
  end

  def remove_shuttle_breakpoint
    count = params[:count].to_i - 1
    @job.remove_shuttle_breakpoint(count)
    respond_to do | format |
      @shuttle_data = @job.get_shuttle_data
      @drivers = Driver.get_active
      @addresses = Address.get_active
      format.js { render 'rerender_shuttle.js.erb' }
    end
  end

  def add_shuttle_passenger
    count = params[:count].to_i
    passenger = Driver.find_by_id(params[:driver_id].to_i)
    unless passenger.nil?
      @job.add_shuttle_passenger passenger, count
      @job.set_passengers
    end
    @shuttle_data = @job.get_shuttle_data
    respond_to do | format |
      format.js { render '_shuttle_passengers.html.erb', :locals => {  :i => count } }
    end
  end

  def remove_shuttle_passenger
    count = params[:count].to_i
    passenger = Driver.find_by_id(params[:driver_id])
    @job.remove_shuttle_passenger passenger, count
    @job.set_passengers
    @shuttle_data = @job.get_shuttle_data
    respond_to do | format |
      format.js { render 'remove_shuttle_passenger.js.erb', :locals => {  :i => count } }
    end
  end

  def change_breakpoint_distance
    if params[:count] == "START" || params[:count] == "END"
      count = params[:count]
    else
      count = params[:count].to_i
    end
    distance = params[:distance].to_i
    @job.change_breakpoint_distance( distance, count )
    respond_to do | format |
      format.json { render 'change_breakpoint_distance.js.erb' }
    end
  end

  def change_breakpoint_address
    @count = params[:count].to_i
    @address = Address.find_by_id(params[:address_id].to_i)
    unless @address.nil?
      @job.change_breakpoint_address( @address, @count )
    end
    respond_to do | format |
      format.json { render 'change_breakpoint_address.js.erb' }
    end
  end

  def change_abroad_start_time
    @count = params[:count].to_i
    @time = params[:time]
    if @time == ":"
      @job.shuttle_data["legs"][@count].delete("abroad_time_start")
      @job.save
    end
    if @time =~ /^[0-2][0-9]:[0-9][0-9]$/
      @job.change_leg_abroad_start_time @time, @count
    end
    respond_to do | format |
      @shuttle_data = @job.get_shuttle_data
      @drivers = Driver.get_active
      @addresses = Address.get_active
      format.js { render 'rerender_shuttle.js.erb' }
    end
  end

  def change_abroad_end_time
    @count = params[:count].to_i
    @time = params[:time]
    if @time == ":"
      @job.shuttle_data["legs"][@count].delete("abroad_time_end")
      @job.save
    end
    if @time =~ /^[0-2][0-9]:[0-9][0-9]$/
      @job.change_leg_abroad_end_time @time, @count
    end
    respond_to do | format |
      @shuttle_data = @job.get_shuttle_data
      @drivers = Driver.get_active
      @addresses = Address.get_active
      format.js { render 'rerender_shuttle.js.erb' }
    end
  end

  def remove_leg_abroad_time_start
    @count = params[:count].to_i
    @job.shuttle_data["legs"][@count].delete("abroad_time_start")
    @job.save
    respond_to do | format |
      @shuttle_data = @job.get_shuttle_data
      @drivers = Driver.get_active
      @addresses = Address.get_active
      format.js { render 'rerender_shuttle.js.erb' }
    end
  end

  def remove_leg_abroad_time_end
    @count = params[:count].to_i
    @job.shuttle_data["legs"][@count].delete("abroad_time_end")
    @job.save
    respond_to do | format |
      @shuttle_data = @job.get_shuttle_data
      @drivers = Driver.get_active
      @addresses = Address.get_active
      format.js { render 'rerender_shuttle.js.erb' }
    end
  end

  def remove_from_current_bill
    @job.set_open
    redirect_to jobs_path
  end

  def add_to_current_bill
    msg = @job.check_for_billing
    if msg == true
      @job.set_to_current_bill
      flash[:notice] = t("jobs.billed")
    else
      flash[:error] = msg
    end
    respond_to do |format|
        format.html { redirect_to jobs_path }
        format.js   { render :layout => false }
        format.json { head :no_content }
    end
  end

  def show_all
    render json: JobsAllDatatable.new(view_context)
  end

  def show_regular_jobs
    render json: JobsDatatable.new(view_context)
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  def print_job
    @job
    respond_to do |format|
      format.html
      headers["Content-Disposition"] = "attachment; filename=\"Auftrag_#{@job.id}.xls\""
      format.xls
    end
  end

  # GET /jobs/new
  def new( job_amount = 1 )
    @job_amount = job_amount
    @job_values = []
    @job = Job.new
    @drivers = Driver.get_active
    @addresses = Address.get_active.order(:address_short)
    @shuttles = []
    @co_driver_ids = []
  end

  def new_shuttle
    @job = Job.new
    @shuttle_cars = ShuttleCar.all
  end

  # GET /jobs/1/edit
  def edit
    @co_driver_ids = @job.get_co_driver_ids
    @number_of_co_drivers = @co_driver_ids.length
    @drivers = Driver.get_active
    @addresses = Address.get_active
    if @job.shuttle?
      @shuttle_data = @job.get_shuttle_data
    end
  end

  def change_to_shuttle
    @job.set_shuttle
    @co_driver_ids = @job.get_co_driver_ids
    @number_of_co_drivers = @co_driver_ids.length
    @drivers = Driver.get_active
    @addresses = Address.get_active
    @shuttle_data = @job.get_shuttle_data
    render "edit"
  end

  def unset_shuttle
    @job.unset_shuttle
    @co_driver_ids = @job.get_co_driver_ids
    @number_of_co_drivers = @co_driver_ids.length
    @drivers = Driver.get_active
    @addresses = Address.get_active
    render "edit"
  end

  def create_shuttle
    logger.info params.inspect
    @job = Job.new
    @job.status = Job::OPEN
    @job.created_by_id = current_user.id
    @job.to_print = false
    if params.has_key?(:shuttle_car)
      shuttle_car = ShuttleCar.where( id: params[:shuttle_car] ).first
      unless shuttle_car.nil?
        @job.apply_shuttle_car_data( shuttle_car )
      end
    end

    if !params[:job].nil? && job_params[:scheduled_collection_time] =~ /\A[0-9][0-9]?\.[0-9][0-9]?\.[1-9][0-9]{3}( [0-2][0-9]:[0-6][0-9])?\z/
      @job.scheduled_collection_time = job_params[:scheduled_collection_time]
      @job.actual_collection_time = @job.scheduled_collection_time
      logger.info job_params[:scheduled_collection_time]
    end
    if !params[:job].nil? && job_params[:scheduled_delivery_time] =~ /\A[0-9][0-9]?\.[0-9][0-9]?\.[1-9][0-9]{3}( [0-2][0-9]:[0-6][0-9])?\z/
      @job.scheduled_delivery_time = job_params[:scheduled_delivery_time]
      @job.actual_delivery_time = @job.scheduled_delivery_time
    end
    @job.save
    @job.set_shuttle
    @co_driver_ids = @job.get_co_driver_ids
    @number_of_co_drivers = @co_driver_ids.length
    @drivers = Driver.get_active
    @addresses = Address.get_active
    if @job.shuttle?
      @shuttle_data = @job.get_shuttle_data
    end
    respond_to do |format|
      if @job.save
        format.html { redirect_to edit_job_path(@job), notice: t("jobs.created") }
      else
        format.html { redirect_to :back }
      end
    end
  end

  # POST /jobs
  # POST /jobs.json
  def create
    job_errors = true
    unless job_params[:scheduled_collection_time] =~ /\A[0-9][0-9]?\.[0-9][0-9]?\.[1-9][0-9]{3}( [0-2][0-9]:[0-6][0-9])?\z/  &&
      job_params[:scheduled_delivery_time] =~ /\A[0-9][0-9]?\.[0-9][0-9]?\.[1-9][0-9]{3}( [0-2][0-9]:[0-6][0-9])?\z/
      error = t("jobs.date_format")
      job_errors = error
      params[:job].except! :scheduled_delivery_time
      params[:job].except! :scheduled_collection_time
    else
      @job = Job.new(job_params)
      @job.status = Job::OPEN
      @job.shuttle = false if @job.shuttle.nil?
      @job.actual_collection_time = @job.scheduled_collection_time
      @job.actual_delivery_time = @job.scheduled_delivery_time
      driver = Driver.find_by( id: job_params[:driver_id])
      @job.driver = driver
      @job.created_by_id = current_user.id
      @job.route_id = Route.find_or_create( params[ :job ][ :from_id ] , params[ :job ][:to_id] )
      if @job.scheduled_collection_time > @job.scheduled_delivery_time
        error = t("jobs.date_error")
        if job_errors == true
          job_errors = [ error ]
        else
          job_errors << error
        end
      end

app/helpers/jobs_helper.rb
module JobsHelper
  def get_abroad_hours time
    unless time.nil? || time.to_time.nil?
      return time.to_time.to_s(:time).split(":").first
    else
      return ""
    end
  end
  def get_abroad_minutes time
    unless time.nil? || time.to_time.nil?
      return time.to_time.to_s(:time).split(":").last
    else
      return ""
    end
  end

  def get_html_abroad_time jobs
    string = "<strong>Gesamt Auslandzeit: #{@job.get_abroad_time}</strong><br>"
    jobs.legs.each_with_index do |leg, i|
      string << "<br>Teilstrecke #{ i + 1 }: " + AbroadTime.calc(  leg.abroad_time_start, leg.abroad_time_end ).to_s
    end
    return string.html_safe
  end
end

app/views/jobs/_co_driver.html.erb
<div class="co_driver row">
  <div class="small-1 column remove-co_driver">
    <br><br><br><%= fa_icon( "minus", text: "" ) %>
  </div>
  <div class="small-11 column">
    <%= index + 1 %>. Fahrer hier filtern <input class="co_drivers_filter %>" type="text">
    <% if @co_driver_ids.nil? %>
      <%= select_tag "co_driver_ids[]", options_from_collection_for_select( @drivers, "id", "fullname_id" ), class: "select_co_drivers" %>
    <% else %>
      <%= select_tag "co_driver_ids[]", options_from_collection_for_select( @drivers, "id", "fullname_id", @co_driver_ids[ index - 1 ].to_s ), class: "select_co_drivers" %>
    <% end %>
  </div>
</div>

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  </div>
  <div class="field">
    <%= f.label :cost_center_id %><br>
    <%= f.number_field :cost_center_id %>
  </div>
  <div class="field">
    <%= f.label :finished %><br>
    <%= f.number_field :finished %>
  </div>
  <div class="field">
    <%= f.label :created_by_id %><br>
    <%= f.number_field :created_by_id %>
  </div>

  <div class="field">
    <%= f.label :from_id %><br>
    <%= f.number_field :from_id %>
  </div>
  <div class="field">
    <%= f.label :to_id %><br>
    <%= f.number_field :to_id %>
  </div>
  <div class="field">
    <%= f.label :shuttle %><br>
    <%= f.check_box :shuttle %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/_shuttle_data_panel.erb
<div class="content active" id="shuttle">
    <%= hidden_field_tag "id", @job.id %>
    <% @shuttle_data.stops.each_with_index do |stop, i| %>
      <div id="<%=i%>">
        <% if i == 0 %>
          <div>
        <% else %>
          <div class="small-12">
        <% end %>
          <div class="small-12 medium-6 columns">
          <%= render "shuttle_stop_header", i: i %>
            Adressen hier filtern <input id="from_filter_<%= i %>" type="text">
            <%= select_tag "addresses_#{ i }", options_from_collection_for_select( @addresses, "id",  "show_address", stop.address_id ), :class => "addresses_select"%>
            <script type="text/javascript">
              $(function(){
                $('#addresses_<%= i %>').filterByText($('#from_filter_<%=i%>'), true);
                $("#from_filter_<%=i%>").keyup(function(){
                  $("#addresses_<%= i %>").change();
                })
              });
            </script>
      	  </div>
          <% if i == 0 %>
            <div class="small-12 medium-2 medium-offset-2 columns shuttle_mileage">
              Kilometerstand Start
              <%= text_field_tag 'start_milage', @job.mileage_collection %>
            </div>
          <% elsif i == @shuttle_data.stops.length - 1 %>
            <div class="small-12 medium-2 columns shuttle_mileage">
                <%= get_html_abroad_time( @job ) %>
            </div>
            <div class="small-12 medium-2 columns shuttle_mileage">
              Kilometerstand Ende
              <%= text_field_tag 'end_milage', @job.mileage_delivery %><br>
              <div class="row">
                <div class="small-12 medium-8 column">Kilometer laut Tacho: </div><div class="small-12 medium-4 column"><span id="complete-distance"><%= @job.distance %></span></div>
              </div><div class="row">
                <div class="small-12 medium-8 column">- Kilometer Stops:</div><div class="small-12 medium-4 column"> <span id="stops-distance"><%= @job.shuttle_stops_distance %></span></div>
              </div><div class="row remaining-mileage-container">
                <div class="small-12 medium-8 column">Verbleibende Km: </div><div class="small-12 medium-4 column"><span id="remaining-milage"><%= @job.get_shuttle_milage_calculation %></span></div>
              </div>
            </div>
          <% else %>
            <div class="small-12 medium-2 medium-offset-1 columns shuttle_remove_stop">
              <%= link_to fa_icon("remove") + "Stop entfernen", job_remove_shuttle_breakpoint_path(:id => @job.id, :count => i.to_s), remote: true, class: "button round" %><br>
            </div>
          <% end %>
        </div>
        <% if @shuttle_data.legs.length > i %>
          <%= render "shuttle_stop", i: i %>
        <% end %>
      </div>
    <% end %>
    <div class="small-12">
      <%= link_to "In normalen Auftrag umwandeln", job_unset_shuttle_path(id: @job.id), class: "button round button-left", data: { confirm: "Shuttle wird zu normalen Auftrag umgewandelt, die Shuttle Daten gehen dadurch verloren. Fortfahren?" } %>
      <%= link_to "Shuttle Auftrag verrechnen", add_job_to_current_bill_path(id: @job.id), method: :post, class: "button round save-and-close" %>
    </div>
</div>

app/views/jobs/_shuttle_passengers.html.erb
<div class="small-10 medium-3 small-offset-2 medium-offset-0 columns shuttle_passengers">
  <div class="small-12 medium-6 column">
  <% @shuttle_data.legs[ i ].driver_ids.each_with_index do |driver_id, j| %>
    <span class="button round success driver-button"><%= link_to fa_icon("remove") + " " + Driver.find_by_id(driver_id).fullname_id, job_remove_shuttle_passenger_path(:id => @job.id, :count => i.to_s, :driver_id => driver_id), remote: true %></span><br>
    <% break if j >= 3 %>
  <% end %>
  </div>
  <div class="small-12 medium-6 column">
  <% if @shuttle_data.legs[ i ].driver_ids.length > 4 %>
      <% @shuttle_data.legs[ i ].driver_ids.each_with_index do |driver_id, j| %>
        <% next if j <= 3 %>
        <span class="button round success driver-button"><%= link_to fa_icon("remove") + " " + Driver.find_by_id(driver_id).fullname_id, job_remove_shuttle_passenger_path(:id => @job.id, :count => i.to_s, :driver_id => driver_id), remote: true %></span><br>
      <% end %>
  <% end %>
  </div>
</div>

app/views/jobs/_shuttle_stop.html.erb
<div class="small-12 column shuttle_driver_row">
  <div class="row">
    <% address_from = @addresses.find_by(id: @shuttle_data.stops[i].address_id ) %>
    <% address_to = @addresses.find_by(id: @shuttle_data.stops[i+1].address_id ) %>
    <h2><span class="address_from_label"><%= address_from.show_address unless address_from.nil? %></span> - <span class="address_to_label"><%=address_to.show_address unless address_to.nil? %></span></h2>
  </div>
  <div class="small-2 column add_stop">
    <%= link_to fa_icon("map-marker") + " Stop hinzufügen", job_add_shuttle_breakpoint_path(:id => @job.id, :count => i.to_s), remote: true, class: "button round" %><br>
  </div>
  <div class="small-10 medium-2 column">
    Fahrer hier filtern <input id="driver_filter_<%=i%>" class="driver_filter" type="text">
    <%= select_tag "driver_ids_#{i}", options_from_collection_for_select( @drivers, "id",  "fullname_id" ), :class => "driver_ids" %>
  </div>
  <div class="small-2 columns">
    <span class="button round add_shuttle_passenger">hinzufügen</span>
  </div>
  <%= render "shuttle_passengers", i: i %>
  <div class="small-1 column">
    Distanz
    <%= text_field_tag "leg[#{i}]distance", @shuttle_data.legs[i].distance, :class => "leg_distance" %>
  </div>
  <div class="abroad-time-container small-12 medium-2 columns">
    <div class="shuttle_abroad_time_start_container row">
      <h3><%= label_tag "abroad_time_start", "Startzeit Auslandsaufenthalt" %></h3><br>
      <% time_start = @shuttle_data.legs[i]["abroad_time_start"].nil? ? nil : @shuttle_data.legs[i]["abroad_time_start"].to_time %>
      <%= time_select :abroad_time_start, "abroad_time_start", {
          include_blank: true,
          selected: time_start,
          time_separator: '<span class="large-2 column center-seperator">:</span>'.html_safe, minute_step: 15},
        { :class => "large-5 columns" } %>&nbsp
        <%= link_to fa_icon( "remove" ), remove_leg_abroad_time_start_path(:id => @job.id, :count => i.to_s), remote: true, title: I18n.t("jobs.leg_abroad_start_delete") %>
    </div>
    <div class="shuttle_abroad_time_end_container row">
      <h3><%= label_tag "abroad_time_end", "Endzeit Auslandsaufenthalt" %></h3><br>
        <% time_end = @shuttle_data.legs[i]["abroad_time_end"].nil? ? nil : @shuttle_data.legs[i]["abroad_time_end"].to_time %>
        <%= time_select :abroad_time_end, "abroad_time_end", {
          include_blank: true,
          selected: time_end,
          time_separator: '<span class="large-2 column center-seperator">:</span>'.html_safe, minute_step: 15},
        { :class => "large-5 columns" } %>&nbsp
        <%= link_to fa_icon( "remove" ), remove_leg_abroad_time_end_path(:id => @job.id, :count => i.to_s), remote: true, title: I18n.t("jobs.leg_abroad_end_delete") %>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(function(){
    $('#driver_ids_<%=i%>').filterByText($('#driver_filter_<%=i%>'), true);
  });
  $('.driver_filter').keypress(function(e) {
    if(e.which == 13) {
        $(this).parent().parent().find(".add_shuttle_passenger").click();
        $(this).val("")
    }
  });
</script>

app/views/jobs/_shuttle_stop_header.html.erb
<% if i == 0 %>
  <h5>
  Adresse für Startpunkt
<% elsif i == @shuttle_data.stops.length - 1 %>
  <h5>
  Adresse für Endpunkt
<% else %>
  <h5>
  Adresse für <%=i.to_s%>. Stop
<%end%>
</h5><br>

app/views/jobs/add_to_current_bill.js.erb
$('#show_jobs').dataTable().fnFilter();

app/views/jobs/change_breakpoint_address.js.erb
<% unless @address.nil? %>
  $('#<%= @count %> .address_from_label').html("<%= @address.show_address %>")
  $('#<%= @count - 1 %> .address_to_label').html("<%= @address.show_address %>")
<% end %>

app/views/jobs/change_co_jobs.js.erb
$('#sidepanel-inner').html("<%= escape_javascript render('sidepanel') %>");
$("#job_details").hide()
$('*[data-role=activerecord_sortable]').activerecord_sortable();
$('#shuttle_jobs').dataTable().fnFilter();

app/views/jobs/edit.html.erb
<% if @job.shuttle? %>
  <ul class="tabs" data-tab>
    <li class="tab-title"><a href="#panel1">Allgemein</a></li>
    <li class="tab-title active"><a href="#shuttle">Shuttlestops</a></li>
  </ul>
  <div class="tabs-content">
  	<div class="content" id="panel1">
<% end %>
<%= render "edit_general" %>
<% if @job.shuttle? %>
	</div>
  <% if @job.shuttle? %>
    <%= render "shuttle_data_panel" %>
  <% end %>
  </div>
<% end %>

app/views/jobs/remove_leg_abroad_time_start.js.erb
alert("asd");
$($(".shuttle_driver_row")[<%= @count %>]).find("#abroad_time_start_abroad_time_start_4i").first().val("");
$($(".shuttle_driver_row")[<%= @count %>]).find("#abroad_time_start_abroad_time_start_5i").first().val("");