config/routes.rb
Rails.application.routes.draw do
  resources :shuttle_cars

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    get 'datatable_i18n', to: 'datatables#datatable_i18n'
  end

  get 'bills/current', to: 'bills#current', as: 'current_bill'
  get 'bills/old', to: 'bills#old', as: 'old_bills'
  post 'bills/add_jobs', to: 'bills#add_jobs', as: 'add_jobs_to_bill'
  post 'bills/delete_current', to: 'bills#delete_current', as: 'delete_current_bill'
  post 'bills/pay/:id', to: 'bills#pay', as: 'pay_bill'
  get 'bills/sixt_bill/:id', to: 'bills#sixt_bill', as: 'sixt_bill'
  get 'bills/complete_bill/:id', to: 'bills#complete_bill', as: 'complete_bill'
  get 'bills/drivers_bill/:id', to: 'bills#drivers_bill', as: 'drivers_bill'
  resources :bills
  devise_for :users
  get 'users/invitation', to: 'jobs#new'
  resources :users

  resources :companies
  get 'routes/show_new', to: 'routes#show_new', as: 'new_routes'
  resources :routes

  resources :drivers

  resources :addresses

  post 'jobs/add_co_driver/', to:'jobs#add_co_driver', as: 'job_add_co_driver'
  get 'jobs/create_sixt/', to: 'jobs#create_sixt', as: 'job_create_sixt'
  post 'jobs/create_shuttle/', to: 'jobs#create_shuttle', as: 'job_create_shuttle'
  get 'jobs/new_sixt/', to: 'jobs#new_sixt', as: 'job_new_sixt'
  get 'jobs/new_shuttle/', to: 'jobs#new_shuttle', as: 'new_shuttle_job'
  get 'jobs/change_to_shuttle/:id', to: 'jobs#change_to_shuttle', as: 'job_change_to_shuttle'
  get 'jobs/unset_shuttle/:id', to: 'jobs#unset_shuttle', as: 'job_unset_shuttle'
  post 'jobs/add_to_current_bill/:id', to: 'jobs#add_to_current_bill', as: 'add_job_to_current_bill'
  post 'jobs/remove_from_current_bill/:id', to: 'jobs#remove_from_current_bill', as: 'remove_job_from_current_bill'
  get 'jobs/add_shuttle_breakpoint/:id', to: 'jobs#add_shuttle_breakpoint', as: 'job_add_shuttle_breakpoint'
  get 'jobs/remove_shuttle_breakpoint/:id', to: 'jobs#remove_shuttle_breakpoint', as: 'job_remove_shuttle_breakpoint'
  get 'jobs/change_breakpoint_distance/:id', to: 'jobs#change_breakpoint_distance', as: 'job_change_breakpoint_distance'
  get 'jobs/change_breakpoint_address/:id', to: 'jobs#change_breakpoint_address', as: 'job_change_breakpoint_address'
  get 'jobs/add_shuttle_passenger/:id', to: 'jobs#add_shuttle_passenger', as: 'job_add_shuttle_passenger'
  get 'jobs/remove_shuttle_passenger/:id', to: 'jobs#remove_shuttle_passenger', as: 'job_remove_shuttle_passenger'
  get 'jobs/change_abroad_start_time/:id', to: 'jobs#change_abroad_start_time', as: 'job_change_abroad_start_time'
  get 'jobs/change_abroad_end_time/:id', to: 'jobs#change_abroad_end_time', as: 'job_change_abroad_end_time'
  get 'jobs/remove_leg_abroad_time_end/:id', to: 'jobs#remove_leg_abroad_time_end', as: 'remove_leg_abroad_time_end'
  get 'jobs/remove_leg_abroad_time_start/:id', to: 'jobs#remove_leg_abroad_time_start', as: 'remove_leg_abroad_time_start'
  get 'jobs/print_job/:id', to: 'jobs#print_job', as: 'print_job'
  post 'jobs/delete/:id', to: 'jobs#destroy', as: 'job_delete'
  get 'jobs/multible_cars/:job_amount', to: 'jobs#multible_cars', as: 'job_multible_cars'
  get 'jobs/set_to_print/:id', to: 'jobs#set_to_print', as: 'job_set_to_print'

  resources :jobs
  get 'jobs_ajax/show_all', to: 'jobs#show_all'
  get 'jobs_ajax/show_regular_jobs', to: 'jobs#show_regular_jobs'

  get 'auslandszeiten/auslandszeiten_pro_fahrer/', to: 'abroad_times#show_driver', as: 'get_abroad_drives_for_driver'
  get 'auslandszeiten/index', to: 'abroad_times#index', as: 'abroad_time_index'
  get 'auslandszeiten/:month_string', to: 'abroad_times#show', as: 'show_abroad_times'

  get 'ueberstunden/fahrer/', to: 'overtimes#show_driver', as: 'get_overtimes_for_driver'
  get 'ueberstunden/index', to: 'overtimes#index', as: 'overtimes_index'
  get 'ueberstunden/:month_string', to: 'overtimes#show', as: 'show_overtimes'

  root 'jobs#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  has_many :jobs

  require 'csv'

  def self.get_old
    old_bills = Bill.where.not( billed_at: nil ).order(billed_at: :desc)
  end

  def self.get_current_with_includes
    current_bill = where( billed_at: nil ).includes( :jobs )[ 0 ]
    if current_bill.nil?
      current_bill = create
    end
    return current_bill
  end

  def to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << ["Rechnung fuer #{self.print_date}"]
      csv << [ "ID", "ABHOLUNG", "LIEFERUNG", "NACH", "VON", "KZ", "KM", "", "", "", "", "EUR", "KSt" ]
      self.jobs.each do |job|
        csv << [job.id, job.actual_collection_date, job.actual_delivery_date, job.to.complete_address, job.from.complete_address,
          job.registration_number, job.route.distance, job.distance, "", job.route.get_calculation_basis, "", job.price_sixt, job.cost_center_id ]
      end
      csv << []
      csv << [ "", "", "", "", "", "", "", "", "", "", "Gesamt",sixt_total]
    end
  end

  def self.get_current
    current_bill = Bill.where( billed_at: nil )[ 0 ]
    if current_bill.nil?
      current_bill = Bill.create
    end
    return current_bill
  end

  def is_current?
    self.billed_at.nil?
  end

  def is_old?
    !self.billed_at.nil?
  end

  def add_jobs jobs
    messages = []
    jobs.each do |job|
      msg = job.check_for_billing
      if msg == true
        job.set_billed( self )
      else
        messages << msg
      end
    end
    if messages.empty?
      return true
    else
      return messages
    end
  end

  def drivers
    drivers_in_bill = []
    self.jobs.each do |job|
      drivers_in_bill << job.driver unless job.driver.nil?
      if job.has_co_drivers?
        job.co_drivers.each do |co_driver|
          drivers_in_bill << co_driver
        end
      end
      if job.is_shuttle?
        job.legs.each do |leg|
          drivers_in_bill << Passenger.where(job_id: job.id).map(&:driver)
        end
      end
    end
    return drivers_in_bill.flatten.uniq
  end

  def get_drives_array( driver )
    jobs = self.jobs.where( driver_id: driver.id ).pluck( :id )
    jobs += Passenger.where(driver_id: driver.id, job_id: self.jobs).pluck(:job_id)
    return jobs
  end

  def get_drives( driver )
    jobs = self.jobs.where( driver_id: driver.id )
    Passenger.where(driver_id: driver.id, job_id: self.jobs).each do |passenger|
      jobs << passenger.job
    end
    return jobs
  end

  def job_price( job, driver )
    if job.shuttle?
      price = job.price_driver_shuttle( driver )
    else
      price = job.price_driver
    end
    return price
  end

  def driver_total( driver )
    total = 0
    jobs = self.get_drives( driver )
    jobs.each do |job| job_price = job_price( job, driver )
      return false unless job_price
      total += job_price
    end
    return total
  end


  def sixt_total
    total = 0
    if self.billed_at.nil?
      sixt = Company.sixt
      self.jobs.each do |job|
        job_price = job.price_sixt_current(sixt)
        return false unless job_price
        total += job_price
      end
    else
      self.jobs.each do |job|
        job_price = job.price_sixt
        return false unless job_price
        total += job_price
      end
    end
    return total
  end

  def pay
    self.price_flat_rate = Company.sixt.price_flat_rate
    self.driver_price_flat_rate = Company.transfair.price_flat_rate
    self.price_per_km = Company.sixt.price_per_km
    self.driver_price_per_km = Company.transfair.price_per_km
    self.billed_at = DateTime.now
    self.save
    self.jobs.each do |job|
      if job.is_shuttle?
        job.final_calculation_basis = Route::PAY_PER_KM
      else
        job.final_calculation_basis = job.route.calculation_basis
      end
      job.set_charged
    end
    return true
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy, :pay, :remove_job, :sixt_bill, :drivers_bill, :complete_bill]
  before_action :check_transfair
  respond_to :html

  def index
    @bills = Bill.all
    respond_with(@bills)
  end

  def old
    @bills = Bill.get_old
    respond_with(@bills)
  end

  def current
    @bill = Bill.get_current_with_includes
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def complete_bill
    respond_to do |format|
      format.html
      format.csv { send_data @bill.to_csv( col_sep: ";").encode('ISO-8859-1', 'UTF-8') }
      headers["Content-Disposition"] = "attachment; filename=\"#{@bill.print_date}_komplett.xls\""
      format.xls
    end
  end

  def sixt_bill
    respond_to do |format|
      format.html
      headers["Content-Disposition"] = "attachment; filename=\"#{@bill.print_date}_Sixt.xls\""
      format.csv { send_data @bill.to_csv( col_sep: ";").encode('ISO-8859-1', 'UTF-8') }
      format.xls { }
    end
  end

  def drivers_bill
    respond_to do |format|
      format.html
      headers["Content-Disposition"] = "attachment; filename=\"#{@bill.print_date}_Fahrer.xls\""
      format.csv { send_data @bill.to_csv( col_sep: ";").encode('ISO-8859-1', 'UTF-8') }
      format.xls { }
    end
  end

  def new
    @bill = Bill.new
    respond_with(@bill)
  end

  def edit
  end

  def create
    @bill = Bill.new(bill_params)
    @bill.save
    respond_with(@bill)
  end

  def update
    @bill.update(bill_params)
    redirect_to @bill
  end

  def destroy
    @bill.jobs.each do |job|
      job.reset_to_current_bill
    end

    @bill.destroy
    redirect_to current_bill_path
  end

  def add_jobs
    @current_bill = Bill.get_current
    msg = @current_bill.add_jobs( Job.get_open )
    if msg != true  && msg.length > 4
      length = msg.length
      msg = msg[0..3]
      msg << "#{ length - 4 } weitere Fehler ..."
    end
    if msg == true
      flash[:notice] = t("bills.billed")
    else
      flash[:error] = msg
    end
    redirect_to current_bill_path
  end

  def delete_current
    @current_bill = Bill.get_current
    @current_bill.jobs.each do |job|
      job.set_open
    end
    @current_bill.destroy
    redirect_to jobs_path
  end

  def pay
    dependencies = @bill.pay
    if dependencies != true && dependencies.length > 4
      length = msg.length
      dependencies = msg[0..3]
      dependencies << "#{ length - 4 } weitere Fehler ..."
    end
    if dependencies == true
      redirect_to @bill
    else
      redirect_to jobs_path, alert: dependencies
    end
  end

  private
    def set_bill
      @bill = Bill.find(params[:id])
    end

    def bill_params
      params.require(:bill).permit(:print_date)
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_drivers.xls.erb
  <%= @bill.drivers.each do |driver| %>
    <Worksheet ss:Name="<%= driver.last_name + "(" + driver.id.to_s + ")" %>">
      <Table x:FullColumns="1" x:FullRows="1" ss:DefaultColumnWidth="60" ss:DefaultRowHeight="15">
      <Column ss:Index="2" ss:AutoFitWidth="0" ss:Width="76.5"/>
     <Column ss:AutoFitWidth="0" ss:Width="70"/>
     <Column ss:AutoFitWidth="0" ss:Width="150"/>
     <Column ss:AutoFitWidth="0" ss:Width="150"/>
     <Column ss:Index="8" ss:AutoFitWidth="0" ss:Width="120"/>
     <Column ss:AutoFitWidth="0" ss:Width="111"/>
     <Column ss:Index="10" ss:AutoFitWidth="0" ss:Width="150"/>
     <Column ss:Index="11" ss:AutoFitWidth="0" ss:Width="150"/>
        <Row ss:Height="20" >
            <Cell ss:StyleID="heading"><Data ss:Type="String">Abrechnung <%= @bill.print_date %> <%= I18n.t( :for ) %> <%= driver.fullname_id %></Data></Cell>
        </Row>
        <Row/>
        <Row>
          <Cell ss:StyleID="borderlinksobenuntendick"><Data ss:Type="String">ID</Data></Cell>
          <Cell ss:StyleID="borderobenuntendick"><Data ss:Type="String">ABHOLUNG</Data></Cell>
          <Cell ss:StyleID="borderobenuntendick"><Data ss:Type="String">LIEFERUNG</Data></Cell>
          <Cell ss:StyleID="borderobenuntendick"><Data ss:Type="String">NACH</Data></Cell>
          <Cell ss:StyleID="borderobenuntendick"><Data ss:Type="String">VON</Data></Cell>
          <Cell ss:StyleID="borderobenuntendick"><Data ss:Type="String">KZ</Data></Cell>
          <Cell ss:StyleID="borderobenuntendick"><Data ss:Type="String">Plan Km</Data></Cell>
          <Cell ss:StyleID="borderobenuntendick"><Data ss:Type="String"><%= I18n.translate( "jobs.actual_distance" )%></Data></Cell>
          <Cell ss:StyleID="borderobenuntendick"><Data ss:Type="String"></Data></Cell>
          <Cell ss:StyleID="borderobenuntendick"><Data ss:Type="String">Verrechungsart</Data></Cell>
          <Cell ss:StyleID="borderobenuntendick"><Data ss:Type="String">Shuttlefahrt</Data></Cell>
          <Cell ss:StyleID="borderrechtsobenuntendick"><Data ss:Type="String">EUR</Data></Cell>
        </Row>
      <% @bill.get_drives( driver ).each do |job| %>
        <Row ss:Height="47">
          <Cell ss:StyleID="<%= "borderlinksobenunten"%>"><Data ss:Type="Number"><%= job.id %></Data></Cell>
          <Cell ss:StyleID="<%= "borderobenunten" %>"><Data ss:Type="String"><%=l job.actual_collection_time unless job.actual_collection_time.nil? %></Data></Cell>
          <Cell ss:StyleID="<%= "borderobenunten" %>"><Data ss:Type="String"><%=l job.actual_delivery_time unless job.actual_delivery_time.nil? %></Data></Cell>
          <Cell ss:StyleID="<%= "borderobenunten" %>"><Data ss:Type="String"><%= job.to.complete_address %></Data></Cell>
          <Cell ss:StyleID="<%= "borderobenunten" %>"><Data ss:Type="String"><%=raw job.from.complete_address %></Data></Cell>
          <Cell ss:StyleID="<%= "borderobenunten" %>"><Data ss:Type="String"><%= job.registration_number %></Data></Cell>
          <Cell ss:StyleID="<%= "borderobenunten" %>"><Data ss:Type="Number"><%= job.route.distance unless job.route.nil? %></Data></Cell>
          <Cell ss:StyleID="<%= "borderobenunten" %>"><Data ss:Type="Number"><%= job.distance %></Data></Cell>
          <Cell ss:StyleID="<%= "borderobenunten" %>"><Data ss:Type="Number"><%= %></Data></Cell>
          <Cell ss:StyleID="<%= "borderobenunten" %>"><Data ss:Type="String"><%= job.route.get_calculation_basis unless job.route.nil?%></Data></Cell>
          <Cell ss:StyleID="<%= "borderobenunten" %>"><Data ss:Type="String"><%= job.shuttle? ? "Ja" : "" %></Data></Cell>
          <Cell ss:StyleID="<%= "preis" %>"><Data ss:Type="Number"><%= @bill.job_price( job, driver ).to_s %></Data></Cell>
        </Row>
        <% if job.is_shuttle? %>
          <Row><Cell ss:Index="12" ss:StyleID="borderrechts"/></Row>
          <Row><Cell ss:StyleID="borderlinks"/><Cell/><Cell/><Cell/><Cell/><Cell/><Cell/><Cell><Data ss:Type="String"></Data></Cell><Cell/><Cell/><Cell/><Cell ss:StyleID="borderrechts"/></Row>
          <Row>
            <Cell ss:StyleID="borderlinks"/>
            <Cell/>
            <Cell/>
            <Cell/>
            <Cell/>
            <Cell/>
            <Cell ss:StyleID="borderlinksobenunten"><Data ss:Type="String">Nach</Data></Cell>
            <Cell ss:StyleID="borderobenunten"><Data ss:Type="String">Von</Data></Cell>
            <Cell ss:StyleID="borderobenunten"><Data ss:Type="String">Distanz</Data></Cell>
            <Cell ss:StyleID="borderobenunten"><Data ss:Type="String">Personen im Wagen</Data></Cell>
            <Cell ss:StyleID="borderrechtsobenunten"><Data ss:Type="String">EUR</Data></Cell>
            <Cell ss:StyleID="borderrechts"/>
          </Row>
          <%= job.legs.each_with_index do |leg, i| %>
            <% if leg.driver_ids.include? driver.id %>
              <Row>
                <Cell ss:StyleID="borderlinks"/>
                <Cell/>
                <Cell/>
                <Cell/>
                <Cell/>
                <Cell/>
                <Cell ss:StyleID="borderlinks"><Data ss:Type="String"><%= Address.where(id: job.stops[i]["address_id"]).first.show_address %></Data></Cell>
                <Cell><Data ss:Type="String"><%= Address.where(id: job.stops[i + 1]["address_id"]).first.show_address %></Data></Cell>
                <Cell><Data ss:Type="Number"><%= leg["distance"] %></Data></Cell>
                <Cell><Data ss:Type="Number"><%= leg["driver_ids"].length %></Data></Cell>
                <Cell ss:StyleID="shuttlezwischenpreis"><Data ss:Type="Number"><%= leg["distance"] * @bill.driver_price_per_km / leg["driver_ids"].length %></Data></Cell>
                <Cell ss:StyleID="borderrechts"/>
              </Row>
            <% end %>
          <% end %>
          <Row>
            <Cell ss:StyleID="borderlinksunten"/>
            <Cell ss:StyleID="borderunten"/>
            <Cell ss:StyleID="borderunten"/>
            <Cell ss:StyleID="borderunten"/>
            <Cell ss:StyleID="borderunten"/>
            <Cell ss:StyleID="borderunten"/>
            <Cell ss:StyleID="borderlinksunten"/>
            <Cell ss:StyleID="borderunten"/>
            <Cell ss:StyleID="borderunten"><Data ss:Type="String">Gesamtpreis Fahrt</Data></Cell>
            <Cell ss:StyleID="borderunten"/>
            <Cell ss:StyleID="shuttlepreis"><Data ss:Type="Number"><%= job.price_driver_shuttle( driver ) %></Data></Cell>
            <Cell ss:StyleID="borderrechtsunten"/>
          </Row>
        <% end %>
      <% end %>
       <Row/>
       <Row>
        <Cell/>
        <Cell/>
        <Cell/>
        <Cell/>
        <Cell/>
        <Cell/>
        <Cell/>
        <Cell/>
        <Cell/>
        <Cell/>
        <Cell><Data ss:Type="String">Gesamtpreis</Data></Cell>
        <Cell ss:StyleID="final_price"><Data ss:Type="Number"><%= @bill.driver_total( driver ).to_s %></Data></Cell>
       </Row>
      </Table>
    </Worksheet>
  <% end %>

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :print_date, "In der Rechnung angezeigtes Datum" %><br>
    <%= f.text_field :print_date %>
  </div>
  <div class="actions">
    <%= f.submit "Rechnungsdatum aktualisieren" %>
  </div>
<% end %>

app/views/bills/_jobs_in_bill.html.erb
<div class= "small-12 column">
  <table id="jobs-in-bill-table" class="display">
    <thead>
      <tr>
        <th>Auftragnummer</th>
        <th>Name</th>
        <th>Von</th>
        <th>Nach</th>
        <th>Datum Abholung</th>
        <th>Datum Lieferung</th>
        <th>Km in Route</th>
        <th><%= t("jobs.actual_distance") %></th>
        <th>Abweichung</th>
        <th>Shuttleauftrag</th>
        <th class="no-sort" ></th>
        <% if @bill.is_current? %>
          <th class="no-sort" ></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @bill.jobs.each do |job| %>
        <tr>
          <td><%= job.id %></td>
          <td><%= job.driver.fullname unless job.driver.nil? %></td>
          <td><%= job.from.show_address %></td>
          <td><%= job.to.show_address %></td>
          <td><%= l job.actual_collection_time.to_date unless job.actual_collection_time.nil? %></td>
          <td><%= l job.actual_delivery_time.to_date unless job.actual_collection_time.nil? %></td>
          <td><%= job.distance_string %></td>
          <td><%= job.distance %></td>
          <td><%= ( job.distance - job.route.distance.to_i ).abs unless job.is_shuttle? %></td>
          <td><%= job.is_shuttle? ? "Ja" : "Nein" %></td>
          <td><%= link_to "anzeigen", job%>
          <% if @bill.is_current? %>
            <td><%= link_to "Aus Rechnung entfernen" , remove_job_from_current_bill_path(job), method: :post %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/bills/complete_bill.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <%= render "styles" %>
  <%= render "sixt" %>
  <%= render "drivers" %>
</Workbook>

app/views/bills/current.html.erb
<div class= "small-12 column">
  <h1>Aktuelle Rechnung</h1>
</div>
<div class="small-12 column padded-column">
  <div class="medium-4 column">
    <%= t("bills.jobs_total") %> <%= @bill.jobs.length %>
  </div>
  <div class="medium-4 column">
     <%= t("bills.jobs_normal") %> <%= @bill.jobs.where(shuttle:false).length %>
  </div>
  <div class="medium-4 column">
    davon Shuttles: <%= @bill.jobs.where(shuttle:true).length %>
  </div>
</div>
<div class="small-12 column padded-column">
Momentaner Preis für Sixt: <span id="price_sixt"><%= number_to_currency @bill.sixt_total %></span>
</div>
<%= render "jobs_in_bill" %>
<div class= "small-12 column">
  <div class= "small-12 medium-3 column">
    <%= button_to "Aktuelle Rechnung entfernen", delete_current_bill_path, data: { confirm: t("bills.reset_to_open") } %>
  </div>
  <div class= "small-12 medium-3 column">
    <%= button_to t( "jobs.bill_open" ), add_jobs_to_bill_path %>
  </div>
  <div class= "small-12 medium-3 column">
    <%= button_to "Rechnung abschließen", pay_bill_path(@bill) %>
  </div>
  <div class= "small-12 medium-3 column">
  </div>
</div>

app/views/bills/edit.html.erb
<div class="small-12 column">
  <h1><%= t("bills.edit_date") %></h1>
</div>
<div class="small-12 column">
  <%= render 'form' %>
</div>
<%= link_to t(:back), old_bills_path %>

app/views/bills/index.html.erb
<h1>Listing bills</h1>

<table>
  <thead>
    <tr>
      <th>Billed at</th>
      <th>Print date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.billed_at %></td>
        <td><%= bill.print_date %></td>
        <td><%= link_to 'Anzeigen', bill %></td>
        <td><%= link_to 'Angezeigtes Datum edieren', edit_bill_path(bill) %></td>
        <td><%= link_to I18n.translate(:delete), bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bills/new.html.erb
<h1>New bill</h1>

<%= render 'form' %>

<%= link_to  t(:back), bills_path %>

app/views/bills/old.html.erb
<div class="small-12 column">
  <h1>Bereits erstellte Rechnungen</h1>
</div>

<table>
  <thead>
    <tr>
      <th>Verrechnet am</th>
      <th>Angedrucktes Datum</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.billed_at.strftime("%d.%m.%Y")  %></td>
        <td><%= bill.print_date %></td>
        <td><%= link_to 'Anzeigen', bill %></td>
        <td><%= link_to 'Angedrucktes Datum edieren', edit_bill_path(bill) %></td>
        <td><%= link_to t(:delete), bill, method: :delete, data: { confirm: t("bills.really_delete_current") } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bills/show.html.erb
<div class="small-12 column">

  <div class="medium-6 small-12 column">
    <p>
      <strong>Verrechnet am:</strong>
      <%=l @bill.billed_at unless @bill.billed_at.nil? %>
    </p>
  </div>
  <div class="medium-6 small-12 column">
    <p>
      <strong>Angedrucktes Datum:</strong>
      <%= @bill.print_date %>
    </p>
  </div>
</div>

<div class="small-12 column">
  <%= render "jobs_in_bill" %>
</div>
<div class="small-12 column">
  <%= link_to 'Datum auf Rechnung editieren', edit_bill_path(@bill) %> |
  <%= link_to t(:back), old_bills_path %><br>
  <%= link_to t("bills.sixt_excel"), sixt_bill_path(format: "xls") %><br>
  <%= link_to t("bills.driver_excel"), drivers_bill_path(format: "xls") %><br>
  <%= link_to "Excel komplett", complete_bill_path(format: "xls") %>
</div>

app/views/bills/sixt_bill.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <%= render "styles" %>
  <%= render "sixt" %>
</Workbook>