config/routes.rb
Rails.application.routes.draw do
  resources :shuttle_cars

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    get 'datatable_i18n', to: 'datatables#datatable_i18n'
  end

  get 'bills/current', to: 'bills#current', as: 'current_bill'
  get 'bills/old', to: 'bills#old', as: 'old_bills'
  post 'bills/add_jobs', to: 'bills#add_jobs', as: 'add_jobs_to_bill'
  post 'bills/delete_current', to: 'bills#delete_current', as: 'delete_current_bill'
  post 'bills/pay/:id', to: 'bills#pay', as: 'pay_bill'
  get 'bills/sixt_bill/:id', to: 'bills#sixt_bill', as: 'sixt_bill'
  get 'bills/complete_bill/:id', to: 'bills#complete_bill', as: 'complete_bill'
  get 'bills/drivers_bill/:id', to: 'bills#drivers_bill', as: 'drivers_bill'
  resources :bills
  devise_for :users
  get 'users/invitation', to: 'jobs#new'
  resources :users

  resources :companies
  get 'routes/show_new', to: 'routes#show_new', as: 'new_routes'
  resources :routes

  resources :drivers

  resources :addresses

  post 'jobs/add_co_driver/', to:'jobs#add_co_driver', as: 'job_add_co_driver'
  get 'jobs/create_sixt/', to: 'jobs#create_sixt', as: 'job_create_sixt'
  post 'jobs/create_shuttle/', to: 'jobs#create_shuttle', as: 'job_create_shuttle'
  get 'jobs/new_sixt/', to: 'jobs#new_sixt', as: 'job_new_sixt'
  get 'jobs/new_shuttle/', to: 'jobs#new_shuttle', as: 'new_shuttle_job'
  get 'jobs/change_to_shuttle/:id', to: 'jobs#change_to_shuttle', as: 'job_change_to_shuttle'
  get 'jobs/unset_shuttle/:id', to: 'jobs#unset_shuttle', as: 'job_unset_shuttle'
  post 'jobs/add_to_current_bill/:id', to: 'jobs#add_to_current_bill', as: 'add_job_to_current_bill'
  post 'jobs/remove_from_current_bill/:id', to: 'jobs#remove_from_current_bill', as: 'remove_job_from_current_bill'
  get 'jobs/add_shuttle_breakpoint/:id', to: 'jobs#add_shuttle_breakpoint', as: 'job_add_shuttle_breakpoint'
  get 'jobs/remove_shuttle_breakpoint/:id', to: 'jobs#remove_shuttle_breakpoint', as: 'job_remove_shuttle_breakpoint'
  get 'jobs/change_breakpoint_distance/:id', to: 'jobs#change_breakpoint_distance', as: 'job_change_breakpoint_distance'
  get 'jobs/change_breakpoint_address/:id', to: 'jobs#change_breakpoint_address', as: 'job_change_breakpoint_address'
  get 'jobs/add_shuttle_passenger/:id', to: 'jobs#add_shuttle_passenger', as: 'job_add_shuttle_passenger'
  get 'jobs/remove_shuttle_passenger/:id', to: 'jobs#remove_shuttle_passenger', as: 'job_remove_shuttle_passenger'
  get 'jobs/change_abroad_start_time/:id', to: 'jobs#change_abroad_start_time', as: 'job_change_abroad_start_time'
  get 'jobs/change_abroad_end_time/:id', to: 'jobs#change_abroad_end_time', as: 'job_change_abroad_end_time'
  get 'jobs/remove_leg_abroad_time_end/:id', to: 'jobs#remove_leg_abroad_time_end', as: 'remove_leg_abroad_time_end'
  get 'jobs/remove_leg_abroad_time_start/:id', to: 'jobs#remove_leg_abroad_time_start', as: 'remove_leg_abroad_time_start'
  get 'jobs/print_job/:id', to: 'jobs#print_job', as: 'print_job'
  post 'jobs/delete/:id', to: 'jobs#destroy', as: 'job_delete'
  get 'jobs/multible_cars/:job_amount', to: 'jobs#multible_cars', as: 'job_multible_cars'
  get 'jobs/set_to_print/:id', to: 'jobs#set_to_print', as: 'job_set_to_print'

  resources :jobs
  get 'jobs_ajax/show_all', to: 'jobs#show_all'
  get 'jobs_ajax/show_regular_jobs', to: 'jobs#show_regular_jobs'

  get 'auslandszeiten/auslandszeiten_pro_fahrer/', to: 'abroad_times#show_driver', as: 'get_abroad_drives_for_driver'
  get 'auslandszeiten/index', to: 'abroad_times#index', as: 'abroad_time_index'
  get 'auslandszeiten/:month_string', to: 'abroad_times#show', as: 'show_abroad_times'

  get 'ueberstunden/fahrer/', to: 'overtimes#show_driver', as: 'get_overtimes_for_driver'
  get 'ueberstunden/index', to: 'overtimes#index', as: 'overtimes_index'
  get 'ueberstunden/:month_string', to: 'overtimes#show', as: 'show_overtimes'

  root 'jobs#index'

end

app/models/abroad_time.rb
class AbroadTime
  MIN_TIME = 8
  PRICE = 0.83

  def self.get_times_per_month date
    jobs = Job.eager_load(:passengers, :driver, :from, :to, :passengers_drivers).where("(shuttle = 'false' and actual_collection_time >= :time_start and " +
      "actual_collection_time <= :time_end and status in (:status) AND abroad_time_start IS NOT NULL AND " +
      "abroad_time_end IS NOT NULL AND abroad_time_start != '' AND " +
      "abroad_time_end != '') OR (shuttle = 'true' AND actual_collection_time >= :time_start AND " +
      "actual_collection_time <= :time_end AND status in (:status))",
      time_start: date.beginning_of_month, time_end: date.end_of_month, status: [ Job::FINISHED, Job::CHARGED ] )
    if jobs.nil?
      return []
    end
    @abroad_times = []
    drivers = []
    jobs_no_empty = jobs.reject { |j| j.shuttle? && j.get_abroad_time == 0 }
    jobs_no_empty.each do |job|
      drivers << job.driver unless job.driver.nil?
      job.passengers_drivers.each do |passenger|
        drivers << passenger
      end
    end

    drivers.uniq!
    drivers = drivers.sort_by{|e| e[:id]}
    drivers.each do |driver|
      drivers_jobs = []
      abroad_line = {name: driver.fullname_id}
      abroad_line[:id] = driver.id
      #drivers_jobs = jobs.where( "jobs.driver_id = :driver_id or passengers.driver_id = :driver_id", driver_id: driver.id )
      abroad_line[:time] = get_abroad_time_for_jobs( driver, jobs )
      #abroad_line[:jobs] = drivers_jobs
      @abroad_times << abroad_line
    end
    return @abroad_times
  end

  def self.driver_total_abroad_time( driver, date, with_jobs = false )
    jobs = Job.eager_load(:passengers).where("(shuttle = 'false' and actual_collection_time >= :time_start and " +
      "actual_collection_time < :time_end and jobs.driver_id = :driver_id and status in (:status) AND " +
      "abroad_time_start IS NOT NULL AND abroad_time_end IS NOT NULL AND abroad_time_start != '' AND " +
      "abroad_time_end != '') or " +
      "( passengers.driver_id = :driver_id and status in (:status) and actual_collection_time >= :time_start and " +
      "actual_collection_time < :time_end)",
      time_start: date.beginning_of_month, time_end: date.beginning_of_month + 1.month, driver_id: driver.id, status: [ Job::FINISHED, Job::CHARGED ] )
    if with_jobs
      return get_abroad_time_for_jobs( driver, jobs ), jobs
    else
      return get_abroad_time_for_jobs driver, jobs
    end
  end

  def self.calc start_time, end_time
    unless ( start_time.nil? || end_time.nil? ) || ( start_time.is_a?( String ) && start_time.blank?) || ( end_time.is_a?( String ) && end_time.blank?)
      end_time = end_time.to_time
      start_time = start_time.to_time
      if start_time > end_time
        return ( ( end_time.to_time + 1.day ) - start_time.to_time ) / 3600
      else
        return ( end_time.to_time - start_time.to_time ) / 3600
      end
    else
      return 0
    end
  end

  private
    def self.get_abroad_time_for_jobs driver, jobs
      total_time = 0
      jobs.group_by(&:group_date).each do |date, job_group|
        day_abroad_time = 0
        job_group.each do |job|
          day_abroad_time += job.get_abroad_time(driver)
        end
        total_time += day_abroad_time if day_abroad_time >= MIN_TIME
      end
      return total_time
    end
end

app/controllers/abroad_times_controller.rb
class AbroadTimesController < ApplicationController
  before_action :check_transfair
  # GET /addresses
  # GET /addresses.json
  def index
    d1 = Date.parse('sep 1 2016')
    d2 = Date.today

    @months = (d1..d2).map{ |m| I18n.l(m, format: :month_with_year) }.uniq.reverse
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
    month, year = params[:month_string].split("_")
    month_number = I18n.t( :month_names, :scope => :date ).index(month.capitalize)
    @date = Date.strptime("#{month_number}.#{year}", "%m.%Y")
    @date_string = "#{month.capitalize} #{year.to_s}"
    @abroad_times = AbroadTime.get_times_per_month( @date )
  end

  def show_driver
    @driver = Driver.find(params[:driver_id])
    @date = params[:date].to_date
    @total_time, @jobs = AbroadTime.driver_total_abroad_time @driver, @date, true
  end
end

app/views/abroad_times/index.html.erb
<h1>Auslandzeiten nach Monat</h1>
<ul>
  <% @months.each do |month| %>
    <li><%= link_to month, show_abroad_times_path(month.downcase.sub(" ", "_" ))%></li>
  <% end %>
</ul>

app/views/abroad_times/show.html.erb
<h1>Auslandzeiten für <%= @date_string %></h1>
<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Gesamtzeit</td>
    </tr>
  </thead>
  <tbody>
  <% @abroad_times.each do |driver_abroad_time| %>
    <tr>
      <td>
        <%= link_to( driver_abroad_time[:name], get_abroad_drives_for_driver_path( date: @date, driver_id: driver_abroad_time[:id] )) %><br>
      </td>
      <td>
        <%= driver_abroad_time[:time] %><br>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/abroad_times/show_driver.html.erb
<h1>Auslandzeiten für <%= @date_string %> von <%= @driver.fullname_id %></h1>
<table>
  <thead>
    <tr>
      <td>Nummer</td>
      <td>Datum</td>
      <td>Strecke</td>
      <td>Gesamtzeit</td>
      <td>Bezahlung</td>
    </tr>
  </thead>
  <tbody>
  <% @jobs.group_by(&:group_date).each do |date, job_group| %>
    <% day_time = 0 %>
    <% job_group.each{ |j| day_time += j.get_abroad_time(@driver)} %>
    <% job_group.each do |job| %>
      <% if job.get_abroad_time > 0 %>
        <tr>
          <td>
            <%= link_to( job.id, job_path(job)) %>
          <td>
            <%=l job.actual_collection_time.to_date %>
          </td>
          <td>
            <%= job.get_route_string %>
          </td>
          <% if day_time < AbroadTime::MIN_TIME %>
            <td>
              <span class="line-trough"><%= job.get_abroad_time(@driver) %></span>
            </td>
            <td>
              0
            </td>
          <% else %>
            <td>
              <% aboad_time = job.get_abroad_time(@driver) %>
              <%= aboad_time %>
            </td>
            <td>
              <%= ( aboad_time * AbroadTime::PRICE ).round(2) %>
            </td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  <% end %>
  <tr>
  <td>
  </td>
  <td>
  </td>
  <td>
  GESAMT:
  </td>
  <td>
    <%= @total_time %>
  </td>
  <td>
    <%= ( @total_time * AbroadTime::PRICE ).round(2) %>
  </td>
</tr>
  </tbody>
</table>