config/routes.rb
Rails.application.routes.draw do
  resources :shuttle_cars

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    get 'datatable_i18n', to: 'datatables#datatable_i18n'
  end

  get 'bills/current', to: 'bills#current', as: 'current_bill'
  get 'bills/old', to: 'bills#old', as: 'old_bills'
  post 'bills/add_jobs', to: 'bills#add_jobs', as: 'add_jobs_to_bill'
  post 'bills/delete_current', to: 'bills#delete_current', as: 'delete_current_bill'
  post 'bills/pay/:id', to: 'bills#pay', as: 'pay_bill'
  get 'bills/sixt_bill/:id', to: 'bills#sixt_bill', as: 'sixt_bill'
  get 'bills/complete_bill/:id', to: 'bills#complete_bill', as: 'complete_bill'
  get 'bills/drivers_bill/:id', to: 'bills#drivers_bill', as: 'drivers_bill'
  resources :bills
  devise_for :users
  get 'users/invitation', to: 'jobs#new'
  resources :users

  resources :companies
  get 'routes/show_new', to: 'routes#show_new', as: 'new_routes'
  resources :routes

  resources :drivers

  resources :addresses

  post 'jobs/add_co_driver/', to:'jobs#add_co_driver', as: 'job_add_co_driver'
  get 'jobs/create_sixt/', to: 'jobs#create_sixt', as: 'job_create_sixt'
  post 'jobs/create_shuttle/', to: 'jobs#create_shuttle', as: 'job_create_shuttle'
  get 'jobs/new_sixt/', to: 'jobs#new_sixt', as: 'job_new_sixt'
  get 'jobs/new_shuttle/', to: 'jobs#new_shuttle', as: 'new_shuttle_job'
  get 'jobs/change_to_shuttle/:id', to: 'jobs#change_to_shuttle', as: 'job_change_to_shuttle'
  get 'jobs/unset_shuttle/:id', to: 'jobs#unset_shuttle', as: 'job_unset_shuttle'
  post 'jobs/add_to_current_bill/:id', to: 'jobs#add_to_current_bill', as: 'add_job_to_current_bill'
  post 'jobs/remove_from_current_bill/:id', to: 'jobs#remove_from_current_bill', as: 'remove_job_from_current_bill'
  get 'jobs/add_shuttle_breakpoint/:id', to: 'jobs#add_shuttle_breakpoint', as: 'job_add_shuttle_breakpoint'
  get 'jobs/remove_shuttle_breakpoint/:id', to: 'jobs#remove_shuttle_breakpoint', as: 'job_remove_shuttle_breakpoint'
  get 'jobs/change_breakpoint_distance/:id', to: 'jobs#change_breakpoint_distance', as: 'job_change_breakpoint_distance'
  get 'jobs/change_breakpoint_address/:id', to: 'jobs#change_breakpoint_address', as: 'job_change_breakpoint_address'
  get 'jobs/add_shuttle_passenger/:id', to: 'jobs#add_shuttle_passenger', as: 'job_add_shuttle_passenger'
  get 'jobs/remove_shuttle_passenger/:id', to: 'jobs#remove_shuttle_passenger', as: 'job_remove_shuttle_passenger'
  get 'jobs/change_abroad_start_time/:id', to: 'jobs#change_abroad_start_time', as: 'job_change_abroad_start_time'
  get 'jobs/change_abroad_end_time/:id', to: 'jobs#change_abroad_end_time', as: 'job_change_abroad_end_time'
  get 'jobs/remove_leg_abroad_time_end/:id', to: 'jobs#remove_leg_abroad_time_end', as: 'remove_leg_abroad_time_end'
  get 'jobs/remove_leg_abroad_time_start/:id', to: 'jobs#remove_leg_abroad_time_start', as: 'remove_leg_abroad_time_start'
  get 'jobs/print_job/:id', to: 'jobs#print_job', as: 'print_job'
  post 'jobs/delete/:id', to: 'jobs#destroy', as: 'job_delete'
  get 'jobs/multible_cars/:job_amount', to: 'jobs#multible_cars', as: 'job_multible_cars'
  get 'jobs/set_to_print/:id', to: 'jobs#set_to_print', as: 'job_set_to_print'

  resources :jobs
  get 'jobs_ajax/show_all', to: 'jobs#show_all'
  get 'jobs_ajax/show_regular_jobs', to: 'jobs#show_regular_jobs'

  get 'auslandszeiten/auslandszeiten_pro_fahrer/', to: 'abroad_times#show_driver', as: 'get_abroad_drives_for_driver'
  get 'auslandszeiten/index', to: 'abroad_times#index', as: 'abroad_time_index'
  get 'auslandszeiten/:month_string', to: 'abroad_times#show', as: 'show_abroad_times'

  get 'ueberstunden/fahrer/', to: 'overtimes#show_driver', as: 'get_overtimes_for_driver'
  get 'ueberstunden/index', to: 'overtimes#index', as: 'overtimes_index'
  get 'ueberstunden/:month_string', to: 'overtimes#show', as: 'show_overtimes'

  root 'jobs#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "MT Transfair" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
    <div class="sticky">
      <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
          <li class="name">
            <h1>MT Trans-Fair</h1>
          </li>
           <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>
        <section class="top-bar-section">
          <ul class="left">
            <li><%= link_to 'Auftrag erfassen', new_job_path %></li>
            <% if current_user.is_intern? %>
              <li><%= link_to 'Shuttle erfassen', new_shuttle_job_path %></li>
              <li><%= link_to t("jobs.all"), jobs_path %></li>

             <li class="has-dropdown">
                <a href="#">Verrechnung</a>
                <ul class="dropdown">
                  <li><%= link_to 'Aktuelle Verrechnung anzeigen', current_bill_path %></li>
                  <li><%= link_to 'Alte Abrechnungen anzeigen', old_bills_path %></li>
                  <li><%= link_to 'Auslandszeiten anzeigen', abroad_time_index_path %></li>
                  <li><%= link_to 'Überstunden anzeigen', overtimes_index_path %></li>
                </ul>
              </li>
              <% if Route.count_new > 0 %>
                <li class="red"><%= link_to "#{Route.count_new} neue Routen!", new_routes_path %></li>
              <% end %>
            <% else %>
              <li><%= link_to t("addresses.add"), new_address_path %></li>
              <li><%= link_to 'Adressen editieren', addresses_path %></li>
              <li><%= link_to 'Benutzerdaten editieren', current_user %></li>
            <% end %>
          </ul>
        </section>

        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">
            <% if current_user.is_intern? %>
              <li class="has-dropdown">
                <a href="#">Administration</a>
                <ul class="dropdown">
                  <li class="has-dropdown">
                    <a href="#">Fahrer</a>
                    <ul class="dropdown">
                      <li><%= link_to 'Fahrer anzeigen', drivers_path %></li>
                      <li><%= link_to t("drivers.add"), new_driver_path %></li>
                    </ul>
                  </li>
                  <li class="has-dropdown">
                    <a href="#">Routen</a>
                    <ul class="dropdown">
                      <li><%= link_to 'Neue Routen', new_routes_path %></li>
                      <li><%= link_to 'Alle Routen', routes_path %></li>
                    </ul>
                  </li>
                  <li class="has-dropdown">
                    <a href="#">Adressen</a>
                    <ul class="dropdown">
                      <li><%= link_to 'Alle Adressen', addresses_path %></li>
                      <li><%= link_to t("addresses.add"), new_address_path %></li>
                    </ul>
                  </li>
                  <li class="has-dropdown">
                    <a href="#">Shuttle Fahrzeuge</a>
                    <ul class="dropdown">
                      <li><%= link_to 'Neues Shuttle Fahrzeug', new_shuttle_car_path %></li>
                      <li><%= link_to 'Alle Shuttle Fahrzeug', shuttle_cars_path %></li>
                    </ul>
                  </li>
                  <li><%= link_to 'Firmen anzeigen', companies_path %></li>
                  <li class="has-dropdown">
                    <a href="#">Benutzer</a>
                    <ul class="dropdown">
                      <li><%= link_to 'Benutzer anzeigen', users_path %></li>
                      <li><%= link_to 'Neuer Benutzer', new_user_invitation_path %></li>
                    </ul>
                  </li>
                </ul>
              </li>
            <% end %>
            <li class="name">
              <h1><%= link_to 'Abmelden', destroy_user_session_path, :method=>'delete' %></h1>
            </li>

          </ul>
        </section>
      </nav>
    </div>
    <% end %>
    <div id="flash-message">
    <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
            <%= content_tag :div, msg %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>
        <% if msg.is_a?(Array) %>
          <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
            <%= content_tag :div, safe_join(msg, "<br>".html_safe) %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="main-wrapper">
      <%= yield %>
    </div>
    <%= javascript_tag do %>
      jQuery.fn.filterByText = function(textbox, selectSingleMatch) {
        return this.each(function() {
          var select = this;
          var options = [];
          $(select).find('option').each(function() {
            options.push({value: $(this).val(), text: $(this).text()});
          });
          $(select).data('options', options);
          $(textbox).bind('change keyup', function() {
            var options = $(select).empty().scrollTop(0).data('options');
            var search = $.trim($(this).val());
            var regex = new RegExp(search,'gi');

            $.each(options, function(i) {
              var option = options[i];
              if(option.text.match(regex) !== null) {
                $(select).append(
                   $('<option>').text(option.text).val(option.value)
                );
              }
            });
            if (selectSingleMatch === true &&
                $(select).children().length === 1) {
              $(select).children().get(0).selected = true;
            }
          });
        });
      };
    <% end %>

  <%= javascript_tag do %>
    $(document).foundation();
    window._url_prefix = '<%= ENV['URL_PREFIX'] %>';
  <% end %>

  </body>
</html>